package api.data;

import java.util.Random; 

public class GenerateData {
	
	public static String getEmail() {
		String email = "autogenerated";
		String provider = "@tekschool.us";
		int randomNumber = (int) (Math.random() * 10000);
		String autoEmail = email + randomNumber + provider;
		return autoEmail;
			
	}
	public static String getPlate() {
		String alphabet = "KBL";
		int randomNumber = (int) (Math.random() * 10000);
		String sign = "-";
		String licensePlate = alphabet + sign + randomNumber;
		
		return licensePlate;
	}
	public static String getPhone() {
		int code = 206;
		int first = (int) (Math.random()*10000);
		int second = (int) (Math.random()*10000);
		String sign = "-";
		String phoneNumber = code + sign + first + sign + second;
		return phoneNumber; 
	}
}
